### ISSUE TITLE
Como adaptar para outros Estados ?

### ISSUE THREAD

**Issue by IWFD** [matheeusaf/vacinometro-covid-19-maprazivel#1]
Seu projeto ficou muito legal, curti mesmo. Gostaria de saber como adaptar para outros estados como MS e MT. Teria como me ajudar ?

**Comment by matheeusaf** [comment]
Fala Israel, beleza?

Cara, como usei um arquivo provido pelo estado de SP, você vai precisar consumir esses dados de outro fonte pois a que usei não funciona para você.

Creio que esses projetos/repositórios de API vão te ajudar:
https://covid19-brazil-api-docs.vercel.app/ (https://github.com/devarthurribeiro/covid19-brazil-api)
https://brasil.io/covid19/ (https://github.com/turicas/covid19-br/blob/master/api.md)
